### ISSUE TITLE
USER STORY: SIGN-UP AND LOGIN PAGE

### ISSUE THREAD

**Issue by markolejman** [markohautala/portfolio-project-4#1]
As a **User** I can **sign up and log in** so that **I can access the service that the website offers**

## Acceptance criteria:
- A page simple in UX/design and that is self explanatory to the user - only the elements that are needed should be present.
- A login and a separate sign-up page.
- There should be relevant texts that guide the user in what needs to be done.

## Tasks:
- [x] Link all the html-pages to each other - good UX-design.
- [x] Relevant form inputs - the login should have different inputs than the signup-page.
- [x] Same colors and theme as the homepage/index.html-file.
- [x] Descriptions and placeholder texts in the different form-unputs.
- [ ] Responsive design - looks good on mobile and desktop and all units in-between.
