### ISSUE TITLE
USER STORY: HOMEPAGE

### ISSUE THREAD

**Issue by markolejman** [markohautala/portfolio-project-4#2]
As a **User** I can **briefly understand what the service is about and how to use it** so that **I can take action and actually get convinced that the service is good and useful**

## Acceptance criteria:
- A homepage that both explains and shows what benefit the service provides.
- The homepage should have clear CTA buttons - for both sign-up and login.
- The website should look appealing in the design.

## Tasks:
- [x] Link all the html-pages to each other - good UX-design.
- [x] Good UX design regarding color choises and that all text is clearly visible and having av good contrast to each other.
- [x] Same colors and theme as the logn and sign-up pages.
- [ ] Pictures that show how a finished product looks from the service.
- [x] Responsive design - looks good on mobile and desktop and all units in-between.
